package com.isl.workflow.constant;

public interface SQLConstant {

    public static String workFlowFormTable = "CREATE TABLE IF NOT EXISTS MST_WORKFLOW_FORM (FORM_NAME  TEXT, FORM_CONFIGURATION TEXT);";

    public static String workFlowMetaData = "CREATE TABLE IF NOT EXISTS WORKFLOW_META_DATA (ID INTEGER, "
            + "TYPE INTEGER, VAL1 TEXT,VAL2 TEXT,VAL3 TEXT,VAL4 TEXT,VAL5 TEXT,VAL6 TEXT,VAL7 TEXT,VAL8 TEXT,VAL9 TEXT,VAL10 TEXT,VAL11 TEXT,VAL12 TEXT" +
            ",VAL13 TEXT,VAL14 TEXT,VAL15 TEXT);";

    public static String workFlowDataTimeStamp = "CREATE TABLE IF NOT EXISTS WORKFLOW_DATA_TS (TYPE_ID INTEGER PRIMARY KEY,  "
            + "LOGIN_TIME TEXT,SAVE_TIME TEXT,NAME TEXT);";

    public static String workFlowDataUserDetail = "CREATE TABLE IF NOT EXISTS WORKFLOW_USERS (ID INTEGER PRIMARY KEY,  "
            + "NAME TEXT,MOBILE TEXT, MAIL TEXT,GROUPS TEXT,CIRCLE TEXT, ZONE TEXT, CLUSTER TEXT);";

    public static String workFlowImages = "CREATE TABLE IF NOT EXISTS WORKFLOW_IMAGES (ID INTEGER,  "
            + "PATH TEXT, NAME TEXT ,TAG TEXT,TIME_STAMP TEXT, LAT TEXT, LONGI TEXT, STATUS TEXT, IP_ADDRESS TEXT, CONSTRAINT PK PRIMARY KEY(PATH,TAG));";

}
