package com.isl.constant;

import java.util.HashMap;

/**
 * Created by dhakan on 2/8/2020.
 */

public class DefaultLevel {

    public static HashMap<String, String> msg(){
        HashMap<String, String> safariMSG = new HashMap<String, String>();
        safariMSG.put("1", "Login Id");
        safariMSG.put("2", "Password");
        safariMSG.put("3", "Forgot Password ?");
        safariMSG.put("4", "Server Configuration");
        safariMSG.put("5", "Login");
        safariMSG.put("6", "Configure IP");
        safariMSG.put("7", "OK");
        safariMSG.put("8", "CANCEL");
        safariMSG.put("9", "Enter IP");
        safariMSG.put("10", "Enter Login ID");
        safariMSG.put("11", "Enter Password");
        safariMSG.put("12", "Configure IP");
        safariMSG.put("13", "Server Not Available");
        safariMSG.put("14", "Enter email Id or mobile number");
        safariMSG.put("15", "Enter valid email address");
        safariMSG.put("16", "Enter valid mobile Number");
        safariMSG.put("17", "No internet connection");
        safariMSG.put("18", "Loading..");
        safariMSG.put("19", "Logging Out ");
        safariMSG.put("20", "Login Successfully");
        safariMSG.put("21", "You are not authorized to access modules.");
        safariMSG.put("22", "Change Password");
        safariMSG.put("23", "Old Password");
        safariMSG.put("24", "New Password");
        safariMSG.put("25", "Retype Password");
        safariMSG.put("26", "Cancel");
        safariMSG.put("27", "Save");
        safariMSG.put("28", "Enter Old Password.");
        safariMSG.put("29", "Enter New Password.");
        safariMSG.put("30", "Enter Retype Password.");
        safariMSG.put("31", "Password does not match with Retype Password.");
        safariMSG.put("32", "Enter New Password different from Old Password.");
        safariMSG.put("33", "Home");
        safariMSG.put("34", "iTower");
        safariMSG.put("35", "Press back once again to Exit");
        safariMSG.put("36", "Successfully logout");
        safariMSG.put("37", "TT checklist not provided by server");
        safariMSG.put("38", "Welcome");
        safariMSG.put("39", "Last Login");
        safariMSG.put("40", "Pending Transactions");
        safariMSG.put("41", "Rejected Transactions");
        safariMSG.put("42", "Notification List");
        safariMSG.put("43", "Notification Setting");
        safariMSG.put("44", "About Us");
        safariMSG.put("45", "Change Password");
        safariMSG.put("46", "Logout");
        safariMSG.put("47", "No Transaction Found");
        safariMSG.put("48", "No Notification Found");
        safariMSG.put("49", "TT Assignment");
        safariMSG.put("50", "TT Updation");
        safariMSG.put("51", "TT Escalation");
        safariMSG.put("52", "PM Schedule");
        safariMSG.put("53", "PM Escalation");
        safariMSG.put("54", "Pop Notification");
        safariMSG.put("55", "No Popup");
        safariMSG.put("56", "Show popup");
        safariMSG.put("57", "Audio Profile");
        safariMSG.put("58", "Notification Tone");
        safariMSG.put("59", "Tone");
        safariMSG.put("60", "Vibrate");
        safariMSG.put("61", "App Version");
        safariMSG.put("62", "Are you sure to Logout?");
        safariMSG.put("63", "Yes");
        safariMSG.put("64", "No");
        safariMSG.put("65", "No internet connection");
        safariMSG.put("66", "No internet connection. Data stored locally in the app.");
        safariMSG.put("67", "No internet connection. Please download Meta data");
        safariMSG.put("68", "You are not authorized for submenus.");
        safariMSG.put("69", "You are not authorized for menus.");
        safariMSG.put("70", "Meta data not provided by server");
        safariMSG.put("71", "");
        safariMSG.put("72", "Incident Management");
        safariMSG.put("73", "Raise Ticket");
        safariMSG.put("74", "My RequestReport");
        safariMSG.put("75", "Ticket Summary Search");
        safariMSG.put("76", "Raise Ticket");
        safariMSG.put("77", "Site ID");
        safariMSG.put("78", "Site Visibility");
        safariMSG.put("79", "Ticket ID");
        safariMSG.put("80", "Ref. Ticket ID");
        safariMSG.put("81", "Equipment");
        safariMSG.put("82", "Severity");
        safariMSG.put("83", "Problem Type");
        safariMSG.put("84", "Problem Start Date");
        safariMSG.put("85", "Problem Start Time");
        safariMSG.put("86", "Problem Start Date Time");
        safariMSG.put("87", "Battery Discharge Start Date");
        safariMSG.put("88", "Battery Discharge Start Time");
        safariMSG.put("89", "Battery Discharge Start Date Time");
        safariMSG.put("90", "Ticked Logged Date Time");
        safariMSG.put("91", "Battery Backup Duration");
        safariMSG.put("92", "Operator Site ID");
        safariMSG.put("93", "Ticket Logged By");
        safariMSG.put("94", "Alarm Detail");
        safariMSG.put("95", "Ticket Type");
        safariMSG.put("96", "Problem Description");
        safariMSG.put("97", "Contacts");
        safariMSG.put("98", "Ticket Status");
        safariMSG.put("99", "ETA");
        safariMSG.put("100", "ETA Time");
        safariMSG.put("101", "ETR");
        safariMSG.put("102", "ETR Time");
        safariMSG.put("103", "RCA Category");
        safariMSG.put("104", "RCA Sub Category");
        safariMSG.put("105", "RCA");
        safariMSG.put("106", "Remarks");
        safariMSG.put("107", "No remarks added");
        safariMSG.put("108", "Ticket Details");
        safariMSG.put("109", "Assigned To");
        safariMSG.put("110", "Operator");
        safariMSG.put("111", "Select Operator");
        safariMSG.put("112", "Operator Exempted");
        safariMSG.put("113", "Select Operator Exempted");
        safariMSG.put("114", "Effected Sites");
        safariMSG.put("115", "Submit");
        safariMSG.put("116", "No TT Checklist Found");
        safariMSG.put("117", "Raised");
        safariMSG.put("118", "ASSIGNED");
        safariMSG.put("119", "RAISED");
        safariMSG.put("120", "Update Ticket");
        safariMSG.put("121", "Update");
        safariMSG.put("122", "No Assigned RequestReport Found");
        safariMSG.put("123", "No Raised RequestReport Found");
        safariMSG.put("124", "Ticket details not available on server");
        safariMSG.put("125", "Select Discharge Start Date first");
        safariMSG.put("126", "Select Problem Start Date first");
        safariMSG.put("127", "Select Problem end Date first");
        safariMSG.put("128", "Select Problem Start Time");
        safariMSG.put("129", "Select Problem End Time");
        safariMSG.put("130", "Select RCA Category");
        safariMSG.put("131", "Select RCA Sub Category");
        safariMSG.put("132", "Enter RCA");
        safariMSG.put("133", "You cannot select problem start date time greater than system date");
        safariMSG.put("134", "You cannot select problem end date time greater than system date");
        safariMSG.put("135", "You cannot select Battery discharge start date time greater than system date");
        safariMSG.put("136", "Do you want to create reference ticket");
        safariMSG.put("137", "Add Reference Ticket");
        safariMSG.put("138", "Select Assigned To");
        safariMSG.put("139", "Problem End Date");
        safariMSG.put("140", "Problem End Time");
        safariMSG.put("141", "No Ticket Found");
        safariMSG.put("142", "My Search");
        safariMSG.put("143", "Age");
        safariMSG.put("144", "Search");
        safariMSG.put("145", "Ticket List");
        safariMSG.put("146", "Wait, Latitude and Longitude is Capturing.");
        safariMSG.put("147", "Energy Management");
        safariMSG.put("148", "My Fuel Purchase");
        safariMSG.put("149", "My Fuel Filling");
        safariMSG.put("150", "Fuel Filling Report");
        safariMSG.put("151", "You cannot select date greater than system date");
        safariMSG.put("152", "Site Id cannot be blank.");
        safariMSG.put("153", "Mobile Genset Deploy Date cannot be blank.");
        safariMSG.put("154", "Reason of Mobile Genset cannot be blank.");
        safariMSG.put("155", "Capacity of Mobile Genset (kVA) cannot be blank.");
        safariMSG.put("156", "Capacity of Mobile Genset (kVA) should have maximum 2 digit after decimal.");
        safariMSG.put("157", "Capacity of Mobile Genset (kVA) should have at least 1 digit after decimal.");
        safariMSG.put("158", "Capacity of Mobile Genset (kVA) cannot be 0.");
        safariMSG.put("159", "Filled Qty. (Ltrs.) cannot be blank.");
        safariMSG.put("160", "Opening Stock (Ltrs.) cannot be blank.");
        safariMSG.put("161", "Genset Meter Reading cannot be blank.");
        safariMSG.put("162", "Grid Meter Reading cannot be blank.");
        safariMSG.put("163", "Capture Minimum");
        safariMSG.put("164", "and Maximum");
        safariMSG.put("165", "Images");
        safariMSG.put("166", "Fuel Filling");
        safariMSG.put("167", "Last Filling Transaction");
        safariMSG.put("168", "Genset Type");
        safariMSG.put("169", "Mobile Genset Deploy Date");
        safariMSG.put("170", "Reason of Mobile Genset");
        safariMSG.put("171", "Capacity of Mobile Genset (kVA)");
        safariMSG.put("172", "Filled Qty. (Ltrs.)");
        safariMSG.put("173", "Opening Stock (Ltrs.)");
        safariMSG.put("174", "Genset Meter");
        safariMSG.put("175", "Genset Meter Reading");
        safariMSG.put("176", "Faulty Since");
        safariMSG.put("177", "Grid Meter");
        safariMSG.put("178", "Grid Meter Reading");
        safariMSG.put("179", "Battery Meter");
        safariMSG.put("180", "Battery Meter Reading");
        safariMSG.put("181", "Submit");
        safariMSG.put("182", "Select Country");
        safariMSG.put("183", "Select county.");
        safariMSG.put("184", "Select Town");
        safariMSG.put("185", "Select Fuel Supplier.");
        safariMSG.put("186", "Select Vendor.");
        safariMSG.put("187", "Fuel Qty. (Ltrs.) cannot be blank.");
        safariMSG.put("188", "Fuel Qty. (Ltrs.) cannot be zero.");
        safariMSG.put("189", "Fuel Amount (MMK) cannot be blank.");
        safariMSG.put("190", "Fuel Amount (MMK) cannot be zero.");
        safariMSG.put("191", "Purchase Date cannot be blank.");
        safariMSG.put("192", "Purchase Time cannot be blank.");
        safariMSG.put("193", "Invalid Purchase Time.");
        safariMSG.put("194", "Fuel Purchase");
        safariMSG.put("195", "Country");
        safariMSG.put("196", "County");
        safariMSG.put("197", "Town");
        safariMSG.put("198", "Fuel Supplier");
        safariMSG.put("199", "Vendor");
        safariMSG.put("200", "Fuel Qty. (Ltrs.)");
        safariMSG.put("201", "Fuel Amount (MMK)");
        safariMSG.put("202", "Purchase Date");
        safariMSG.put("203", "Purchase Time");
        safariMSG.put("204", "Submit");
        safariMSG.put("205", "Last Filling Transaction");
        safariMSG.put("206", "From Date cannot be greater than Current Date");
        safariMSG.put("207", "To Date cannot be greater than Current Date");
        safariMSG.put("208", "Site Id cannot be blank.");
        safariMSG.put("209", "From Date cannot be blank.");
        safariMSG.put("210", "To Date cannot be blank.");
        safariMSG.put("211", "From Date cannot be greater than To Date");
        safariMSG.put("212", "Report Not Found");
        safariMSG.put("213", "Filler Details");
        safariMSG.put("214", "Fill Date");
        safariMSG.put("215", "Latitude");
        safariMSG.put("216", "Longitude");
        safariMSG.put("217", "Distance(Kms.)");
        safariMSG.put("218", "Filling Transaction Report");
        safariMSG.put("219", "Scheduled");
        safariMSG.put("220", "Pending");
        safariMSG.put("221", "Verified");
        safariMSG.put("222", "Missed");
        safariMSG.put("223", "Done");
        safariMSG.put("224", "Preventive Maintenance");
        safariMSG.put("225", "No Activity Found");
        safariMSG.put("226", "PM Checklist not available. Please contact system admin.");
        safariMSG.put("227", "No Image Found");
        safariMSG.put("228", "Capture");
        safariMSG.put("229", "Select");
        safariMSG.put("230", "Enter");
        safariMSG.put("231", "General Inspection");
        safariMSG.put("232", "DG Maintenance");
        safariMSG.put("233", "Special DG Maintenance");
        safariMSG.put("234", "Schedule");
        safariMSG.put("235", "Filling Schedule");
        safariMSG.put("236", "PM Schedule");
        safariMSG.put("237", "Activity");
        safariMSG.put("238", "Change Language");
        safariMSG.put("239", "General");
        safariMSG.put("240", "Click Image");
        safariMSG.put("241", "General PM");
        safariMSG.put("242", "DG PM");
        safariMSG.put("243", " Battery PM");
        safariMSG.put("244", " Special DG PM");
        safariMSG.put("245", "From Date");
        safariMSG.put("246", "To Date");
        safariMSG.put("247", "Problem End Date Time");
        safariMSG.put("248", "Ticket Logged Date Time");
        safariMSG.put("249", "Select Severity");
        safariMSG.put("250", "Select Problem Type");
        safariMSG.put("251", "Select Battery Discharge Start Time");
        safariMSG.put("252", "Wait, Latitude and Longitude is Capturing.");
        safariMSG.put("253", "Maximum");
        safariMSG.put("254", "Images can be uploaded.");
        safariMSG.put("255", "Enter");
        safariMSG.put("256", "Select");
        safariMSG.put("257", "Capture Minimum");
        safariMSG.put("258", "and Maximum");
        safariMSG.put("259", "Select Genset No.");
        safariMSG.put("260", "Select Language");
        safariMSG.put("261", "Forgot Password");
        safariMSG.put("262", "Open");
        safariMSG.put("263", "Assign");
        safariMSG.put("264", "Resolved");
        safariMSG.put("265", "Closed");
        safariMSG.put("266", "Trouble Ticket");
        safariMSG.put("267", "No Data Found");
        safariMSG.put("268", "Enter email Id associated with this account");
        safariMSG.put("269", "OR");
        safariMSG.put("270", "Enter mobile no. associated with this account");
        safariMSG.put("271", "Clear");
        safariMSG.put("272", "Select ringtone for notifications");
        safariMSG.put("273", "IMAGE 1~IMAGE 2~IMAGE 3~IMAGE 4~IMAGE 5");
        safariMSG.put("274", "IMAGE 1~IMAGE 2~IMAGE 3~IMAGE 4~IMAGE 5");
        safariMSG.put("275", "IMAGE 1~IMAGE 2~IMAGE 3~IMAGE 4~IMAGE 5");
        safariMSG.put("276", "Email Id");
        safariMSG.put("277", "Mobile Number");
        safariMSG.put("278", "PM Review");
        safariMSG.put("279", "Add/View Spare Parts?");
        safariMSG.put("280", "Add/View Spare Parts");
        safariMSG.put("281", "Spare Part");
        safariMSG.put("282", "Spare Parts");
        safariMSG.put("283", "Quantity");
        safariMSG.put("284", "Add");
        safariMSG.put("285", "Spare parts quantity can't be blank.");
        safariMSG.put("286", "Enter Quantity.");
        safariMSG.put("287", "Filling Mode");
        safariMSG.put("288", "Fuel in Tank");
        safariMSG.put("289", "Actual CPH");
        safariMSG.put("290", "Vendor");
        safariMSG.put("291", "Do you want to exit");
        safariMSG.put("292", "User does not belongs to region of the site.");
        safariMSG.put("293", "Sync");
        safariMSG.put("294", "Spare parts has been added update ticket to save permanently.");
        safariMSG.put("295", "Successfull sync.");
        safariMSG.put("296", "Search By");
        safariMSG.put("297", "Capture Pre Photo");
        safariMSG.put("298", "Click Pre Image");
        safariMSG.put("299", "Pre Images");
        safariMSG.put("300", "Pre Photo");
        safariMSG.put("301", "Post Images");
        safariMSG.put("302", "Click Post Image");
        safariMSG.put("303", "Genset Meter Replacement Date");
        safariMSG.put("304", "Grid Meter Replacement Date");
        safariMSG.put("305", "Genset meter replacement date cannot be blank");
        safariMSG.put("306", "Grid meter replacement date cannot be blank");
        safariMSG.put("307", "Add Serial Number");
        safariMSG.put("308", "Serial no. cannot be blank.");
        safariMSG.put("309", "details not available");
        safariMSG.put("310", "Quantity exceed ! Maximum quantity should be");
        safariMSG.put("311", "Action");
        safariMSG.put("312", "Sno");
        safariMSG.put("313", "Serial Number");
        safariMSG.put("314", "Average DG Run Hour Per Day");
        safariMSG.put("315", "PM Missed");
        safariMSG.put("316", "Status");
        safariMSG.put("317", "Reviewer Status");
        safariMSG.put("318", "");
        safariMSG.put("5080", "You are using older version. Please download latest mobile app from play store.");
        safariMSG.put("20001", " Site Maintenance");
        safariMSG.put("20002", "Genset Maintenance");
        safariMSG.put("20003", "Site Audit");
        safariMSG.put("20004", "Generator Overhaul");
        safariMSG.put("20006", "");
        safariMSG.put("20007", "");
        safariMSG.put("401", "Approval");
        safariMSG.put("402", "DFR Approval");
        safariMSG.put("403", "Spare Part Approval");
        safariMSG.put("404", "PENDING");
        safariMSG.put("405", "APPROVED");
        safariMSG.put("406", "REJECTED");
        safariMSG.put("407", "Spare Part Approval");
        safariMSG.put("408", "Pending DFR Approval");
        safariMSG.put("409", "DFR Approval");
        safariMSG.put("410", "Filler : ");
        safariMSG.put("411", "Genset Type : ");
        safariMSG.put("412", "DFR Approval");
        safariMSG.put("414", "Site ID");
        safariMSG.put("415", "Date");
        safariMSG.put("416", "Standard CPH");
        safariMSG.put("417", "Actual CPH");
        safariMSG.put("418", "Mobile");
        safariMSG.put("419", "DFR");
        safariMSG.put("420", "Sensor");
        safariMSG.put("421", "Reject");
        safariMSG.put("422", "Transaction Type");
        safariMSG.put("424", "Fill Qty.(Ltrs)");
        safariMSG.put("425", "Genset Meter Reading");
        safariMSG.put("426", "Grid Meter Reading");
        safariMSG.put("427", "Opening Stock");
        safariMSG.put("428", "Site Motorable");
        safariMSG.put("429", "Last Approved Transaction Details");
        safariMSG.put("430", "Remarks");
        safariMSG.put("431", "Submit");
        safariMSG.put("432", "Last Transaction Date : ");
        safariMSG.put("433", "Last Fill Qty.(Ltrs) : ");
        safariMSG.put("434", "Last Fill Genset Reading : ");
        safariMSG.put("435", "Last Opening Stock : ");
        safariMSG.put("436", "Last Fill Grid Meter Reading : ");
        safariMSG.put("437", "Spare Part : ");
        safariMSG.put("438", "Qty : ");
        safariMSG.put("439", "Vendor : ");
        safariMSG.put("440", "Pending");
        safariMSG.put("441", "Approved");
        safariMSG.put("442", "Rejected");
        safariMSG.put("443", "Site ID");
        safariMSG.put("444", "Transaction Date");
        safariMSG.put("445", "Ticket ID/PM Activity Type");
        safariMSG.put("447", "Spare Part Name");
        safariMSG.put("448", "Quantity");
        safariMSG.put("449", "Serial No.");
        safariMSG.put("450", "Remarks");
        safariMSG.put("451", "Last Transaction Details");
        safariMSG.put("452", "Approved");
        safariMSG.put("453", "Rejected");
        safariMSG.put("454", "Submit");
        safariMSG.put("455", "Spare Part Date : ");
        safariMSG.put("456", "Transaction Type : ");
        safariMSG.put("457", "Ticket Id/PM Activity Type : ");
        safariMSG.put("458", "Last Transaction Details");
        safariMSG.put("459", "Spare Part Approval");
        safariMSG.put("460", "Transaction Type");
        safariMSG.put("461", "Rejection Reason");
        safariMSG.put("462", "Category");
        safariMSG.put("463", "Remarks");
        safariMSG.put("464", "Submit");
        safariMSG.put("465", "Verify");
        safariMSG.put("466", "Reject");
        safariMSG.put("467", "Rejected");
        safariMSG.put("468", "Do you want to reject this Transaction?");
        safariMSG.put("469", "Category");
        safariMSG.put("470", "Remarks");
        safariMSG.put("471", "Date");
        safariMSG.put("472", "RESOLVED");
        safariMSG.put("473", "Media Tag: ");
        safariMSG.put("474", "Time Stamp: ");
        safariMSG.put("500", "Type");
        safariMSG.put("501", "Once transaction rejected,will not be roll back. Please be sure before rejecting.");
        safariMSG.put("507", "Sync Pending Transactions");
        safariMSG.put("508", "Confirmation");
        safariMSG.put("509", "Do you want to save or discard the checklist? On Discard checklist will not be saved locally in mobile app.");
        safariMSG.put("510", "Discard");
        safariMSG.put("511", "Place a QR code inside the viewfinder rectangle to scan it.");
        safariMSG.put("512", "Do you want to delete photo for");
        safariMSG.put("654","Incident Management");
        safariMSG.put("655","Preventive Maintenance");
        safariMSG.put("656","Energy ");
        safariMSG.put("657","Schedule ");
        safariMSG.put("658","Alarm Management");
        safariMSG.put("659","Assets ");
        safariMSG.put("660","Report ");
        safariMSG.put("921","Approval ");
        safariMSG.put("955","Health &amp; Safetyy");
        safariMSG.put("964","SafKPLC ");
        safariMSG.put("515", "ReSubmit");
        safariMSG.put("516", "Activity Type");
        safariMSG.put("517", "Assign Group");
        safariMSG.put("518", "Assign User(s)");
        safariMSG.put("519", "Review Group");
        safariMSG.put("520", "Review User(s)");
        safariMSG.put("521", "Review Plan Date");
        safariMSG.put("522", "Schedule Date");
        safariMSG.put("523", "Schedule Site Activity");
        safariMSG.put("513", "Planned Verify Date :");
        safariMSG.put("514", "Done Date :");
        safariMSG.put("524", "Fuel Level");
        safariMSG.put("525", "Action Taken");
        safariMSG.put("526","New Request");
        safariMSG.put("527","Health &amp; Safety RequestReport");
        safariMSG.put("528","Search RequestReport");
        safariMSG.put("529","Activity");
        safariMSG.put("530","Sub Activity");
        safariMSG.put("531","Severity");
        safariMSG.put("532","Add Health &amp; Safety Ticket");
        safariMSG.put("533","Decription");
        safariMSG.put("534","Assigned To");
        safariMSG.put("535","Opco Site Id");
        safariMSG.put("536","Site Visibilty");
        safariMSG.put("537","Reference ticket");
        safariMSG.put("538","Equipment");
        safariMSG.put("539","Problem Start Date");
        safariMSG.put("540","Problem Start Time");
        safariMSG.put("541","Battery Discharge Start Date");
        safariMSG.put("542","Battery Discharge Start Time");
        safariMSG.put("543","Alarm Details");
        safariMSG.put("544","Operator");
        safariMSG.put("545","Exempt Operator");
        safariMSG.put("546","Effected Sites");
        safariMSG.put("547","Upload TT Checklist");
        safariMSG.put("548","Upload Health &amp; Safety Checklist");
        safariMSG.put("549","View  Health &amp; Safety Checklist");
        safariMSG.put("550","Update Ticket");
        safariMSG.put("552","Alarm History");
        safariMSG.put("553","Audit Trail");
        safariMSG.put("554", "Update Ticket");
        safariMSG.put("555","First Level Approval");
        safariMSG.put("556","Final Level Approval");
        safariMSG.put("557","Ticket ID");
        safariMSG.put("558","Problem Start Date and Time");
        safariMSG.put("559","Problem End Date and Time");
        safariMSG.put("560","Ticket Logged Date and Time");
        safariMSG.put("561","Ticket Logged By");
        safariMSG.put("562","Battery Discharge Start Date and Time");
        safariMSG.put("563","Sub Activity Details");
        safariMSG.put("564","ETA");
        safariMSG.put("565","ETA Time");
        safariMSG.put("566","ETR");
        safariMSG.put("567","ETR Time");
        safariMSG.put("568","RCA Category");
        safariMSG.put("569","RCA Sub Category");
        safariMSG.put("570","RCA");
        safariMSG.put("571","Ticket Status");
        safariMSG.put("572","Audit Trails");
        safariMSG.put("573","Rejection Category");
        safariMSG.put("574","Rejection Remarks");
        safariMSG.put("575","ASSIGNED");
        safariMSG.put("576","RAISED");
        safariMSG.put("577","RESOLVED");
        safariMSG.put("578","CLOSED");
        safariMSG.put("579","OPEN");
        safariMSG.put("580","More Transaction Details");
        safariMSG.put("737","13210");
        safariMSG.put("738","13212");
        safariMSG.put("581","This App is not install in you phone. Do you want to install app from Google Play Store.");
        safariMSG.put("746","Transaction Id");
        safariMSG.put("747","Do you wants to add more reference ticket?");
        safariMSG.put("137","Add Reference Ticket");
        safariMSG.put("830","SiteId cannot be blank");

        safariMSG.put("858","Location Alert");
        safariMSG.put("859","Oops! Your current location is outside of xxx meter from the site. Ensure you are within xxx meter from the site. Checklist submission is restricted.");
        safariMSG.put("860","Do you want to continue?");
        safariMSG.put("861","1. Unable to submit the checklist. Ensure you are within xxx meter from the site.");
        safariMSG.put("862","2. Please make sure that your mobile device have accurate GPS.");
        safariMSG.put("863","3. The checklist is saved as draft until you are within the allowed submission radius.");
        safariMSG.put("864","I’m on the site.");
        safariMSG.put("865","Please take photo of the GPS coordinates using GPS device \"E.G. Garmin\" and showing the sign board in the background as shown below and also escalate the issue to TAWAL-OE and send the required photo to request for site coordinates change in TMS.");
        safariMSG.put("872","Site Coordinate Change Instruction.");
        safariMSG.put("873","Is Satisfied");
        safariMSG.put("874","12");
        safariMSG.put("875","Asset Id");
        return safariMSG;
    }
}
