package com.isl.leaseManagement.roomKotlin.dao

import androidx.room.*
import com.isl.leaseManagement.dataClasses.responses.CandidateDetailsAPIResponse
import io.reactivex.Single

@Dao
interface CandidateDetailsDao {

    // Insert a single CandidateDetailsAPIResponse, replacing in case of conflict
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertCandidateDetails(candidateDetails: CandidateDetailsAPIResponse): Single<Long>

    // Insert multiple CandidateDetailsAPIResponse records
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertAllCandidateDetails(candidateDetailsList: List<CandidateDetailsAPIResponse>): Single<List<Long>>

    @Query("SELECT * FROM CandidateDetailsAPIResponse WHERE autoGeneratedId = :id")
    fun getCandidateDetailsByAutoGeneratedId(id: Int): Single<CandidateDetailsAPIResponse>

    // Update a specific CandidateDetailsAPIResponse
    @Update
    fun updateCandidateDetails(candidateDetails: CandidateDetailsAPIResponse): Single<Int>

    // Delete a specific CandidateDetailsAPIResponse
    @Delete
    fun deleteCandidateDetails(candidateDetails: CandidateDetailsAPIResponse): Single<Int>

    // Delete all CandidateDetailsAPIResponse records
    @Query("DELETE FROM CandidateDetailsAPIResponse")
    fun deleteAllCandidateDetails(): Single<Int>
}
