package com.isl.leaseManagement.dataClasses.responses

import androidx.room.Entity
import androidx.room.PrimaryKey

class ExistingCandidateListResponse :
    ArrayList<ExistingCandidateListResponse.ExistingCandidateListResponseItem>() {
    @Entity
    data class ExistingCandidateListResponseItem(
        @PrimaryKey(autoGenerate = true) val autoGeneratedId: Int = 0, //for room unique identification,not from api
        val _Id: Int?,
        val landlordId: String?,
        val landlordName: String?,
        val propertyId: String?,             //getting this in both api i.e. existing candidate and link existing candidate so this will be used for mapping correct candidate data
        val propertyCity: String?,
        val propertyDistrict: String?,        //until here getting data from existing captured candidate list
        val candidateId: Int?,            //now from here getting after saving existing captured candidate by link existing candidate API
        val isPropertyValid: Boolean? = false,    //from saving/liking candidate api and for all below fields as well
        val isLandlordValid: Boolean? = false,
        val isAccountValid: Boolean? = false,
        val isDelegateValid: Boolean? = false,
        val isDocValid: Boolean? = false,
    )
}
