package com.isl.leaseManagement.bts.captureCandidate.propertyDetails

import android.os.Bundle
import androidx.databinding.DataBindingUtil
import com.google.android.material.tabs.TabLayout
import com.isl.leaseManagement.base.BaseActivity
import com.isl.leaseManagement.utils.AppConstants
import infozech.itower.R
import infozech.itower.databinding.ActivityPropertyDetailsBinding

class PropertyDetailsActivity : BaseActivity() {

    private lateinit var binding: ActivityPropertyDetailsBinding
    private var autoGeneratedID = 0
    private var candidateOrLandlordName:String? = "NA"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = DataBindingUtil.setContentView(this, R.layout.activity_property_details)
        init()
    }

    private fun init() {
        checkIfDataAlreadySaved()
        addTabsAndAttachClicks()
        setClickListeners()
    }

    private fun setClickListeners() {
        binding.backIv.setOnClickListener { finish() }
    }

    private fun checkIfDataAlreadySaved() {
        autoGeneratedID = intent.getIntExtra(
            AppConstants.IntentKeys.autoGeneratedId,
            0
        )   // so, 0 means new candidate

        candidateOrLandlordName = intent.getStringExtra(
            AppConstants.IntentKeys.candidateOrLandlordName
        ) ?: "NA"
        binding.candidateOrLandlordNameTv.text = candidateOrLandlordName
    }

    private fun addTabsAndAttachClicks() {
        binding.tabLayout.addTab(binding.tabLayout.newTab().setText("Essential property"))
        binding.tabLayout.addTab(binding.tabLayout.newTab().setText("Comprehensive property"))

        val bundle = Bundle()
        bundle.putString(AppConstants.IntentKeys.autoGeneratedId, autoGeneratedID.toString())
        bundle.putString(AppConstants.IntentKeys.candidateOrLandlordName, candidateOrLandlordName)
        loadFragmentInFrameLayout(   //initial
            EssentialPropertyFragment(),
            binding.fragmentContainer.id,
            bundle
        )

        binding.tabLayout.addOnTabSelectedListener(object : TabLayout.OnTabSelectedListener {
            override fun onTabSelected(tab: TabLayout.Tab?) {
                when (tab?.position) {
                    0 -> {
                        loadFragmentInFrameLayout(
                            EssentialPropertyFragment(),
                            binding.fragmentContainer.id,
                            bundle
                        )
                    }

                    1 -> {
                        showToastMessage("Comprehensive Clicked!")
                    }
                }
            }

            override fun onTabUnselected(tab: TabLayout.Tab?) {
            }

            override fun onTabReselected(tab: TabLayout.Tab?) {
            }
        })

    }

}